
figures/defect_prone_f1_comparison.pdf: plotf1.py
	 python plotf1.py figures/defect_prone_f1_comparison.pdf


figures/defect_prone_rec20_comparison.pdf: plotrec20.py
	python plotrec20.py figures/defect_prone_rec20_comparison.pdf

figures/defect_prone_popt_comparison.pdf: plotpopt.py
	python plotpopt.py figures/defect_prone_popt_comparison.pdf

figures/dp_oss6_f1_vs_nchanges.pdf: plotoss6f1.py
	python plotoss6f1.py figures/dp_oss6_f1_vs_nchanges.pdf	

figures/dp_oss6_f1_vs_dratio.pdf: plotoss6f1.py
	python plotoss6f1.py figures/dp_oss6_f1_vs_dratio.pdf	

figures/dp_oss6_f1_vs_locchange.pdf: plotoss6f1.py
	python plotoss6f1.py figures/dp_oss6_f1_vs_locchange.pdf

figures/dp_oss6_f1_vs_ndevavrg.pdf: plotoss6f1.py
	python plotoss6f1.py figures/dp_oss6_f1_vs_ndevavrg.pdf

figures/dp_f1_vs_defect_others.pdf: plotf1vsdr.py
	python plotf1vsdr.py figures/dp_f1_vs_defect_others.pdf

